# Create a Role in the default namespace that grants access to the agones api
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fleet-allocator
  namespace: default
  labels:
    app: fleet-allocator
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["allocation.agones.dev"]
  resources: ["gameserverallocations"]
  verbs: ["create"]
- apiGroups: ["agones.dev"]
  resources: ["fleets"]
  verbs: ["get"]

---
# Create a ServiceAccount that will be bound to the above role
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-allocator
  namespace: default
  labels:
    app: fleet-allocator

---
# Bind the fleet-allocator ServiceAccount to the fleet-allocator Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fleet-allocator
  namespace: default
  labels:
    app: fleet-allocator
subjects:
- kind: ServiceAccount
  name: fleet-allocator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fleet-allocator
