telemetry:
  zpages:
    enable: "true"
  jaeger:
    enable: "false"
    agentEndpoint: "open-match-jaeger-agent:6831"
    collectorEndpoint: "http://open-match-jaeger-collector:14268/api/traces"
  prometheus:
    enable: "true"
    endpoint: "/metrics"
    serviceDiscovery: "true"
  stackdriver:
    enable: "false"
    gcpProjectId: "replace_with_your_project_id"
    metricPrefix: "open_match"
  zipkin:
    enable: "false"
    endpoint: "/zipkin"
    reporterEndpoint: "zipkin"
  reportingPeriod: "1m"