# Define a Service for the fleet-allocator
apiVersion: v1
kind: Service
metadata:
  name: fleet-allocator-backend
  labels:
    app: fleet-allocator
spec:
  selector:
    app: fleet-allocator
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: fleet-allocator  # retrieve port from deployment config

---
# Deploy a pod to run the fleet-allocator code
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-allocator
  namespace: default
  labels:
    app: fleet-allocator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-allocator
  template:
    metadata:
      labels:
        app: fleet-allocator
    spec:
      serviceAccount: fleet-allocator
      containers:
      - name: fleet-allocator
        image: gcr.io/sailaxman-kasna/allocator:latest
        imagePullPolicy: Always
        ports:
        - name: fleet-allocator
          containerPort: 8000
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5                    
